"""Cross-check the ℚ kernel against `fixtures/*.json`.

Invariants:
- ``fixtures/*.json`` was generated by ``scripts/build_fixtures.py`` from
  the same Fraction kernel; running the kernel here MUST reproduce the
  identical rationals (same numerator and denominator after reducing).
- When the user runs the v18.16 simulator export
  (``scripts/export_simulator_fixtures.py``) on their Mac, the same
  files must match byte-for-byte.

If the fixtures are missing, the tests rebuild them so the suite always
runs without manual setup.
"""
from __future__ import annotations

import json
import sys
from fractions import Fraction
from pathlib import Path

import pytest

from vedic.kernel import conservation_exact as ce
from vedic.kernel import z2_primitives as se
from vedic.kernel.q import Q16


REPO = Path(__file__).resolve().parents[3]
FIXTURE_DIR = REPO / "fixtures"


def _require_fixtures() -> None:
    """Refuse to run if the committed reference is absent.

    This used to call ``build_fixtures.py`` when a fixture was missing --
    regenerating the reference *from the same kernel the gate then compares
    against*, so an empty ``fixtures/`` produced a confident "bit-exact" pass.

    To be exact about what that cost: the comparisons still ran, and would
    still have caught nondeterminism between the two executions. What they
    could no longer do is falsify *correctness* -- the reference agreed with
    the kernel because it had just been written from it. A gate that cannot
    be wrong about the thing it exists to check is not a weak gate; it is a
    different gate than the one everyone was citing.

    The fixtures are a committed reference, not a build artefact. If they are
    missing the answer is that the gate cannot run, not that it should
    manufacture something to agree with.
    """
    missing = [p.name for p in (
        FIXTURE_DIR / "psi_inputs.json",
        FIXTURE_DIR / "sutra_outputs.json",
        FIXTURE_DIR / "conservation_residuals.json",
    ) if not p.exists()]
    if missing:
        raise SystemExit(
            f"fixtures/ is missing {', '.join(missing)}. These are the "
            f"committed reference this gate checks against; they are tracked "
            f"in git. Restore them (git checkout -- fixtures/) rather than "
            f"rebuilding: scripts/build_fixtures.py writes them from the same "
            f"kernel under test, so a rebuilt fixture cannot falsify anything."
        )


@pytest.fixture(scope="session", autouse=True)
def fixtures_present() -> None:
    _require_fixtures()


def _obj_to_frac(obj: dict[str, int]) -> Fraction:
    return Fraction(int(obj["num"]), int(obj["den"]))


def _objs_to_q16(objs: list[dict[str, int]]) -> Q16:
    return tuple(_obj_to_frac(o) for o in objs)


def _load(name: str) -> dict[str, object]:
    with (FIXTURE_DIR / name).open("r", encoding="utf-8") as f:
        return json.load(f)


def test_psi_inputs_roundtrip() -> None:
    data = _load("psi_inputs.json")
    inputs = data["inputs"]
    assert isinstance(inputs, list) and len(inputs) >= 1
    for psi_obj in inputs:
        psi = _objs_to_q16(psi_obj)
        assert all(isinstance(x, Fraction) for x in psi)


def test_sutra_outputs_match_kernel() -> None:
    data = _load("sutra_outputs.json")
    for rec in data["records"]:
        psi = _objs_to_q16(rec["input"])

        assert _objs_to_q16(rec["S1"]) == se.s1_eka_adhikena(psi)
        assert _objs_to_q16(rec["S2"]) == se.s2_nikhilam(psi)
        assert _objs_to_q16(rec["S4"]) == se.s4_paravartya(psi)
        assert _objs_to_q16(rec["S5"]) == se.s5_shunyam_samya(psi)
        assert _objs_to_q16(rec["S6"]) == se.s6_anurupya_shunyam(psi)
        sym, anti = se.s7_sankalana_vyavakalana(psi)
        assert _objs_to_q16(rec["S7_sym"]) == sym
        assert _objs_to_q16(rec["S7_anti"]) == anti
        assert _objs_to_q16(rec["S8"]) == se.s8_puranapuranabhyam_fill(psi)
        assert _objs_to_q16(rec["S9"]) == se.s9_chalana_kalanabhyam(psi)
        assert _objs_to_q16(rec["S10"]) == se.s10_yavadunam_tavadunikrtya(psi)
        assert _objs_to_q16(rec["S11"]) == se.s11_vyasti_samasti(psi)
        assert _objs_to_q16(rec["S12"]) == se.s12_shesanyankena_charamena(psi)
        assert _objs_to_q16(rec["S13"]) == se.s13_sopantyadvayamantyam_last2(psi)
        assert _objs_to_q16(rec["S14"]) == se.s14_ekanyunena_purvena(psi)
        assert _objs_to_q16(rec["S15"]) == se.s15_gunitasamucchaya_product(psi)
        assert _objs_to_q16(rec["S16"]) == se.s16_gunaka_samucchaya(psi)
        assert _obj_to_frac(rec["S18"]) == se.s18_adyamadyena_antyamantyena(psi)
        assert _objs_to_q16(rec["S19"]) == se.s19_lopana_sthapanabhyam(psi)
        assert _objs_to_q16(rec["S20"]) == se.s20_vilokanam_spect(psi)
        assert _objs_to_q16(rec["S21"]) == se.s21_dhvajanka_flag(psi)
        s22_ref = se.s22_parity_complement(psi)
        s22_fix = tuple(_obj_to_frac(o) for o in rec["S22"])
        assert s22_fix == s22_ref
        assert _objs_to_q16(rec["S24"]) == se.s24_kevalaih_saptakam(psi)
        assert _objs_to_q16(rec["S25"]) == se.s25_vestana_circular(psi)
        assert _objs_to_q16(rec["S26"]) == se.s26_yavadunam_square(psi)
        assert _obj_to_frac(rec["S27"]) == se.s27_samuccaya_gunitah(psi)
        assert _objs_to_q16(rec["S28"]) == se.s28_lopana_restore(psi)
        assert _objs_to_q16(rec["S29"]) == se.s29_mean_drive(psi)


def test_conservation_residuals_match_kernel() -> None:
    data = _load("conservation_residuals.json")
    psi_data = _load("psi_inputs.json")
    inputs = [_objs_to_q16(p) for p in psi_data["inputs"]]

    n = len(inputs)
    assert len(data["records"]) == n * 3

    for i, rec in enumerate(data["records"]):
        psi = inputs[i // 3]
        trace = _obj_to_frac(rec["trace_sum"])
        r1, r2, r3, r4 = ce.all_residuals(psi, trace)
        assert _obj_to_frac(rec["R1"]) == r1
        assert _obj_to_frac(rec["R2"]) == r2
        assert _obj_to_frac(rec["R3"]) == r3
        assert _obj_to_frac(rec["R4"]) == r4
