#!/usr/bin/env node
/* Run every suite in this unpack, in one command.
 *
 *     node run-checks.mjs            every suite
 *     node run-checks.mjs --fast     all but the slow ones, named below
 *     node run-checks.mjs --list     what would run, and nothing else
 *
 * GENERATED by faraday/build-zip.mjs from its SUITES list. Editing this file in
 * place is pointless: the next build overwrites it. Add the suite there.
 *
 * Nothing here skips. A suite that cannot run fails, and the exit code is
 * non-zero, because a run that quietly omitted a suite and said "all passed"
 * would be worse than no runner at all.
 */
import { spawnSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const SUITES = [
  {"name":"faraday/check-kernel.mjs","file":"faraday/check-kernel.mjs","slow":false,"browser":false},
  {"name":"faraday/check-standalone.mjs","file":"faraday/check-standalone.mjs","slow":false,"browser":false},
  {"name":"dns/check-dns.mjs","file":"dns/check-dns.mjs","slow":false,"browser":false},
  {"name":"dns/check-disc.mjs","file":"dns/check-disc.mjs","slow":false,"browser":false},
  {"name":"dns/check-wasm-build.mjs","file":"dns/check-wasm-build.mjs","slow":false,"browser":false},
  {"name":"dns/check-cell3d.mjs","file":"dns/check-cell3d.mjs","slow":true,"browser":false},
  {"name":"dns/check-cell3d-wasm.mjs","file":"dns/check-cell3d-wasm.mjs","slow":true,"browser":false},
  {"name":"boundary/boundarykernel.test.js","file":"boundary/boundarykernel.test.js","slow":false,"browser":false},
  {"name":"fsi/check-coupled-affine.mjs","file":"fsi/check-coupled-affine.mjs","slow":false,"browser":false},
  {"name":"dns/check-page.mjs","file":"dns/check-page.mjs","slow":false,"browser":true}
];

const argv = process.argv.slice(2);
for (const a of argv)
  if (a !== '--fast' && a !== '--list'){
    console.error(`unknown option ${a}. Known: --fast, --list.`);
    process.exit(2);
  }
const fast = argv.includes('--fast');
const list = argv.includes('--list');
const run = SUITES.filter(s => !(fast && s.slow));

if (list){
  for (const s of run)
    console.log(`${s.name}${s.slow ? '   (slow)' : ''}${s.browser ? '   (needs Chrome)' : ''}`);
  process.exit(0);
}

const browserSuites = run.filter(s => s.browser).map(s => s.name);
if (browserSuites.length)
  console.log(`note: ${browserSuites.join(', ')} needs a Chrome or Chromium binary. `
    + `It refuses rather than skipping; set CHROME=/path/to/chrome if it is not found.\n`);

const results = [];
for (const s of run){
  process.stdout.write(`=== ${s.name}${s.slow ? '   (slow -- minutes)' : ''}\n`);
  const t0 = Date.now();
  const r = spawnSync(process.execPath, [join(HERE, s.file)],
                      { stdio: ['ignore', 'pipe', 'pipe'], encoding: 'utf8' });
  const secs = (Date.now() - t0)/1000;
  const out = (r.stdout || '') + (r.stderr || '');
  const tail = out.trimEnd().split('\n').slice(-3).join('\n');
  const okRun = r.status === 0;
  console.log(tail);
  console.log(`--- ${s.name}: ${okRun ? 'PASS' : 'FAIL'} in ${secs.toFixed(1)} s\n`);
  if (!okRun && !tail) console.log(out);
  results.push({ name: s.name, ok: okRun, secs });
}

console.log('summary');
for (const r of results)
  console.log(`  ${r.ok ? 'PASS' : 'FAIL'}  ${r.name}  ${r.secs.toFixed(1)} s`);
const bad = results.filter(r => !r.ok);
if (bad.length){
  console.log(`\n${bad.length} of ${results.length} suites FAILED.`);
  process.exit(1);
}
console.log(`\nall ${results.length} suites passed.`);
